; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
; Bibliothèques partagées par les deux environnements
lib_deps =
    ESP32Async/ESPAsyncWebServer @ ^3.6.0
    ESP32Async/AsyncTCP @ ^3.3.2
    bblanchon/ArduinoJson @ ^7.2.0

; Options de compilation communes
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_ASYNC_TCP_RUNNING_CORE=0

board_build.filesystem = littlefs

; Flash & PSRAM

; Partitions
board_build.partitions = partitions.csv

; 2. Carte d'origine : ESP32 classique
[env:esp32dev]
platform = espressif32
board = esp32dev
build_flags = 
    ${env.build_flags}
    -D TARGET_ESP32_DEV


; 3. Nouvelle carte : ESP32-S3 de 4D Systems
[env:4d_systems_esp32s3_gen4_r8n16]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
build_flags = 
    ${env.build_flags}
    -D TARGET_4D_SYSTEMS
    -D ARDUINO_USB_CDC_ON_BOOT=1
board_build.flash_size = 16MB
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi

